version: "3"

services:
  api:
    container_name: api
    build: .
    restart: always
    depends_on:
      - database
    ports:
      - 3333:3333
  database:
    container_name: mongo-database
    image: mongo:latest
    restart: always
    volumes:
      - books-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=books
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=books
    ports:
      - 27017:27017

volumes:
  books-data:
