version: "3.8"
services:
  api-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-dev
    volumes:
      - .:/usr/app
    restart: always
    depends_on:
      - database-dev
    ports:
      - 3334:3333
    command: yarn dev:server
  database-dev:
    container_name: mongo-database-dev
    image: mongo:latest
    restart: always
    volumes:
      - books-data-dev:/data/db
    environment:
      - MONGO_INITDB_DATABASE=books
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=books
    ports:
      - 27019:27017
  migration:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: migration-dev
    volumes:
      - .:/usr/app
    depends_on:
      - database-dev
    command: yarn typeorm migration:run

volumes:
  books-data-dev:
